name: Deploy Laravel to Hostinger  

on:
  pull_request:
    types:
      - closed  # Triggers only when a pull request is merged
    branches:
      - main  # Runs only when merged into main

jobs:
  deploy:
    if: github.event.pull_request.merged == true  # Runs only if a PR is merged into main
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy Only Changed Files via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTINGER_IP }}
        username: ${{ secrets.HOSTINGER_SSH_USER }}
        password: ${{ secrets.HOSTINGER_SSH_PASS }}
        port: ${{ secrets.HOSTINGER_PORT }}
        source: "."  # Upload only changed files
        target: "/home/${{ secrets.HOSTINGER_USERNAME }}/public_html/fleet/"
        overwrite: true  # Overwrite existing files
        rm: false  # Do NOT delete files like vendor/ or .env

    - name: Run Migrations & Clear Cache
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOSTINGER_IP }}
        username: ${{ secrets.HOSTINGER_SSH_USER }}
        password: ${{ secrets.HOSTINGER_SSH_PASS }}
        port: ${{ secrets.HOSTINGER_PORT }}
        script: |
          echo "✅ Connected to Hostinger Server"

          # Change to the Laravel project directory
          cd /home/${{ secrets.HOSTINGER_USERNAME }}/public_html/fleet/framework || exit 1
          
          # Print current directory
          echo "📌 Current Directory:"
          pwd

          # List all files
          echo "📂 Listing files in framework directory:"
          ls -lah  

          # Check if artisan exists
          echo "🔍 Checking if artisan exists:"
          if [ -f "artisan" ]; then
            echo "✅ Artisan file found!"
          else
            echo "❌ Artisan file missing!"
            exit 1
          fi

          # Run Laravel Commands and Log Output
          echo "🚀 Running Laravel Migrations & Clearing Cache"

          echo "🔄 Running: php artisan migrate --force"
          php artisan migrate --force

          echo "🧹 Running: php artisan cache:clear"
          php artisan cache:clear

          echo "⚙️ Running: php artisan config:clear"
          php artisan config:clear

          echo "🛠 Running: php artisan route:clear"
          php artisan route:clear

          echo "🎨 Running: php artisan view:clear"
          php artisan view:clear

          echo "✅ Deployment & Artisan Commands Completed Successfully!"
