name: Deploy Laravel to Hostinger  

on:
  pull_request:
    types:
      - closed  # Triggers only when a pull request is merged
    branches:
      - main  # Deploys only when merged into main

jobs:
  deploy:
    if: github.event.pull_request.merged == true  # Ensures it runs only when PR is merged
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy Only Changed Files via Rsync
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avz --ignore-existing  # Sync changes without deleting existing files
        path: .  # Upload everything in the repo
        remote_path: "/home/${{ secrets.HOSTINGER_USERNAME }}/public_html/fleet/"
        remote_host: ${{ secrets.HOSTINGER_IP }}
        remote_user: ${{ secrets.HOSTINGER_SSH_USER }}
        remote_key: ${{ secrets.HOSTINGER_SSH_KEY }}  # Use SSH Key authentication

    - name: Run Migrations & Clear Cache
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOSTINGER_IP }}
        username: ${{ secrets.HOSTINGER_SSH_USER }}
        password: ${{ secrets.HOSTINGER_SSH_PASS }}
        port: ${{ secrets.HOSTINGER_PORT }}
        script: |
          cd /home/${{ secrets.HOSTINGER_USERNAME }}/public_html/fleet/framework

          # Run migrations & clear cache
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
